src/api.ts

Closes #20 
Notes:
- Enables incremental autovacuum for the database, which can be triggered by calling `db.pragma('incremental_vacuum')`
- We don't have any api methods that potentially delete a lot of data yet, so there's no logic to actually do any vacuuming at the moment. Once functionality such as deleting tiles + tilesets is supported, we can just call the vacuum since the database will have been initiated with this enabled.
- See https://github.com/digidem/mapeo-mapserver/issues/20#issuecomment-1120026720 for example script that shows how effective this can be

chore: enable vacuuming of db

---

src/app.test.ts
src/lib/mbtiles.test.ts
src/lib/upstream_requests_manager.test.ts

not entirely sure if this will fix anything but I meant to return the cleanup promise for the tests, which tape can then await properly. might explain why CI has occasionally failed due to a hanging test

chore: potentially prevent tests from hanging

---

src/api.ts
src/lib/mbtiles_import_worker.js

noticed an issue where the `finally` call on the piscina instance would execute before the final two messages from the worker (final progress and complete) would be received by the port. for some reason, moving the post message calls in the worker to before we close the db instances solved the problem, although I'm a little puzzled as to why (does one of those calls send some kind of signal that piscina listens for?)

fix: fix race condition with piscina and worker

---

src/app.test.ts
src/lib/upstream_requests_manager.test.ts

didn't really occur to me until now that we should be using tape's `teardown` for closing server instances in tests. previously, we called `cleanup` at the end of a test but that doesn't handle the case of when uncaught exceptions occur within a test, which will cause the server to never close and the test to hang.

use teardown hook for tests

---

src/api.ts

Seems like the cause of the v8 error we were getting (https://github.com/WiseLibs/better-sqlite3/issues/842) might have been caused by terminating the worker threads without first closing the DB instance. This PR attempts to fix that by doing a graceful shutdown of workers (it waits for them to finish) before closing the server completely. This PR also adds the `minThreads: 1` option to Piscina, since otherwise I think Piscina opens a worker thread for every CPU available on startup. This minimizes the initial overhead of thread creation.

fix: Fix v8 error with graceful onClose cleanup

---

src/public/map_preview.html
src/routes/styles.ts

A very quick implementation that enables viewing of a map preview rendered with mapbox-gl-js. Append `/preview` to a Style URL to view that style rendered in the browser. Mainly useful for development.
Built on #54 since it uses fastify-static and that's already in #54.

feat: HTML map previews

---

src/api/errors.ts
src/api/imports.ts
src/api/index.ts
test/e2e/tilesets-import.test.js

Closes #58 
Notes:
- Went with a naive approach of deleting the style (which deletes the associated tileset) if the import fails to start. Ideally we'd prevent them from being created in the first place, but would likely entail some messy coordination of messages

fix: remove stray style and tileset when import fails to start

---

src/api/imports.ts
src/api/styles.ts
test/e2e/tilesets-import.test.js

Addresses feedback from https://github.com/digidem/mapeo-map-server/pull/56#discussion_r942860866
Also includes other smaller unrelated chores from that previous PR

fix: use mbtiles file name as fallback style name when importing as new tileset

---

src/api/errors.ts
src/api/tiles.ts
src/api/tilesets.ts
src/lib/tiles.ts
src/lib/utils.ts
src/routes/fonts.ts
src/routes/tilesets.ts
test/e2e/glyphs.test.js
test/e2e/styles.test.js
test/e2e/tilesets-crud.test.js
test/test-helpers/constants.js

Fixes #57 
Notes:
- Similar to the glyphs implementation, we need to forward and adjust certain responses we send based on the upstream request and internet connectivity. If a tile isn't found locally:
- if upstream responds with 4XX, ~we forward the response~ respond with a 404
- if upstream responds with 5XX, we respond with a 404
- if there's no internet connectivity, we respond with a 404

fix: return proper responses for get tile endpoint

---

src/api/styles.ts
src/api/tiles.ts
src/api/tilesets.ts
src/lib/stylejson.ts
src/lib/utils.ts
src/routes/tilesets.ts
test/e2e/styles.test.js

Fixes #63 
When creating a style, we save the normalized upstream url (i.e. http-based url) for each source we create for it, which allows us to make proper/valid upstream requests when needed.

fix: properly handle upstream behavior for fetching tilesets

---

API.md
src/api/imports.ts
src/lib/imports.ts
src/lib/mbtiles_import_worker.d.ts
src/lib/mbtiles_import_worker.js
test/e2e/imports.test.js

Notes:
- Noticed a failing import test that was skipped and decided to address it. If the read row has invalid data, we update the import record to reflect the error state and send an `error` message to the main thread.
- Question: currently we set the import record's `error` field to `UNKNOWN` in this case, although maybe it would be more useful to have a slightly more descriptive error that reflects the unexpected bad data

fix: improve handling of import progress endpoint when import error occurs

---

src/api/imports.ts
test/e2e/imports.test.js
test/e2e/tilesets-import.test.js

Noticed while attempting to integrate into mapeo mobile, but when our message timeout expires, it cancels the Piscina task and attempts to delete the style if the worker never sent its first message to main thread. However, upon cancellation, the Piscina task also attempts to delete the style. This causes an undesirable unhandled error.
Now we defer the style deletion to the cancelled Piscina task and remove that logic from the message timeout handler (or maybe it should it be the other way around?). Ideally a test would be added simulating the worker timeout, but not entirely sure how to create that situation via a test, so left a comment for now.

fix: avoid redundant attempt at deleting style when import worker timeout occurs

---

.github/workflows/node.yml
package-lock.json
package.json

Closes #66 
The latest version of [`fontnik`](https://github.com/mapbox/node-fontnik/blob/master/CHANGELOG.md#070) adds support for Node 16, which means we can actually test against it for CI

chore: upgrade fontnik and include node 16 in CI

---

README.md
package-lock.json
package.json
server.ts
src/api/index.ts
test/test-helpers/create-server.js

Closes #92 
**This is a breaking change**, as it updates the function signature of the export `createServer` function to accept an instance of a BetterSqlite3 database instead of a file path string.
- Removes `better-sqlite3` from `depedencies` field
- Adds `better-sqlite3` to `peerDependencies` and `devDependencies` fields
- Updates `MapServerOptions` from `{ dbPath: string }` to `{ database: Database }`

feat!: accept database instance instead of path when creating server 

---

prisma/migrations/20240207033957_init/migration.sql
prisma/schema.prisma
test/e2e/styles.test.js

The [original issue][0] has useful background for this change:
> Calling api.deleteStyle can take a long time under the following conditions:
>
> * multiple relatively exclusive tilesets exist in the db
> * sufficient number of tile data (say at least ~100 MB)
>
> Replicate this by doing two mbtiles imports, waiting for them to complete, and deleting either one of the styles associated with it.  The example I tried imported a small map (~10 MB) and the Terrastories default offline map (~150 MB), and attempting to delete either map style.
>
> Bottleneck seems to be this query (takes about 16 seconds on my machine):
>
> ```
> DELETE FROM TileData WHERE tilesetId IN (${tilesetsSqlList})`
> ```
Why was this query so slow?
To find out, I compiled[^A] SQLite with [profiling][1] and ran the …

perf: speed up style deletion

---

src/api/styles.ts

Previously, we ran a query that was basically like this:
```javascript
db.prepare(
`DELETE FROM my_table WHERE id IN (1, 2, 3)`
).run()
```
Now, we run the query like this:
```javascript
db.prepare(
`DELETE FROM my_table WHERE id IN (?, ?, ?)`
).run([1, 2, 3])
```
Though I think it was never a problem in practice, this prevents SQL injection attacks if the IDs contained SQL somehow.

chore: clean up SQL bindings when deleting styles

---

package-lock.json
package.json
types/@mapbox__whoots-js.d.ts

[@types/mapbox__whoots-js was recently added][0] so we can use it and delete our own types.
[0]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68550

chore: use upstream types for @mapbox/whoots-js

---

src/api/sprites.ts
src/api/styles.ts
src/api/tilesets.ts
src/lib/migrations.ts
test/unit/migrations.test.js

*This change is not urgent.*
Sometimes, you want to know whether at least one row matches a query. In my opinion, [SELECT EXISTS] is the best way to do this for two reasons:
1. It states intent more clearly than other methods.
2. It is faster than other methods.[^faster]
Currently, we use SELECT COUNT(*) and check if the count is > 0. This patch moves things to use SELECT EXISTS.
[^faster]: Intuitively, I expected SELECT EXISTS to be faster because you don't need the precise count—you just need to know whether a query returns any results at all. But how much faster? I wrote a simple [profiling script] to test this. On my machine, it was between ~1.5x faster when checking for the existence of a single row by primary key and ~1300x faster when a full table scan would have been required. In …

chore: use SELECT EXISTS where applicable

---

package-lock.json
package.json
src/lib/mbtiles_import_worker.js

This upgrades TypeScript from v4.7.4 to v5.3.3. This required a small number of type-related changes: updating the `@typescript-eslint` dependencies, updating the dependencies for `@types/eventsource`, and fixing a small type error in the import worker.
The `dist/` folder looks very similar after this, though (1) source map files changed (2) TypeScript now adds the `declare` keyword in `.d.ts` files, such as:
```diff
-export type GlyphsResult = {
+export declare type GlyphsResult = {
```
There were no changes to any compiled `.js` files after this change.

chore: update TypeScript to v5

---

API.md
src/map-server.ts
src/routes/tilesets.ts
test/e2e/tilesets-crud.test.js
test/e2e/tilesets-import.test.js

This is the next step in [a larger refactor][0] where we replace the HTTP API with a JS one.
[0]: https://github.com/digidem/mapeo-map-server/issues/111
BREAKING CHANGE: `GET /tilesets` replaced with `listTilesets()`

refactor!: move tileset list from HTTP API to JS API

---

API.md
src/api/styles.ts
src/map-server.ts
src/routes/styles.ts
test/e2e/styles.test.js
test/e2e/tilesets-crud.test.js
test/e2e/tilesets-import.test.js

This is the next step in [a larger refactor][0] where we replace the HTTP API with a JS one.
[0]: https://github.com/digidem/mapeo-map-server/issues/111
BREAKING CHANGE: `GET /styles` replaced with `listStyles()`

refactor!: move style list from HTTP API to JS API

---

.github/workflows/node.yml
package-lock.json
package.json

This removes Node 16 support, given that (1) it is deprecated (2) it [is no longer used in CoMapeo][0].
[0]: https://github.com/digidem/CoMapeo-mobile/pull/194

chore!: drop Node 16 support
